"""create users tableс

Revision ID: 13dd9299d73d
Revises: e430346e457b
Create Date: 2025-06-07 01:20:39.140007

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "13dd9299d73d"
down_revision: Union[str, None] = "e430346e457b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
