"""orders3

Revision ID: 15f1a9b00cd2
Revises: e13ac435bb7e
Create Date: 2025-06-23 17:30:09.751532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f1a9b00cd2'
down_revision: Union[str, None] = 'e13ac435bb7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Если не передан, считается как quantity * price',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Если не передан, считается как quantity * price',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    # ### end Alembic commands ###
