"""messages1

Revision ID: 60d85552b620
Revises: 97614b184354
Create Date: 2025-06-23 16:32:41.492703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d85552b620'
down_revision: Union[str, None] = '97614b184354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'replied_at')
    op.drop_column('messages', 'reply')
    # ### end Alembic commands ###
