"""add total to orders

Revision ID: 92bc788af3ac
Revises: 8ce810d717eb
Create Date: 2025-06-06 20:10:21.347614

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "92bc788af3ac"
down_revision: Union[str, None] = "8ce810d717eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
