"""messages

Revision ID: 97614b184354
Revises: 6982b2926d73
Create Date: 2025-06-23 16:29:02.218001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97614b184354'
down_revision: Union[str, None] = '6982b2926d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('messages_user_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_order_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_order_id_fkey'), 'messages', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(op.f('messages_user_id_fkey'), 'messages', 'users', ['user_id'], ['id'])
    op.alter_column('messages', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
